name: Continuous Integration

on:
  push:
    tags:
      - "v[1-9]+.[0-9]+.[0-9]+"
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ~1.22.2

      - name: Gather dependencies
        run: go mod download

      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}