name: Continuous Integration

on:
  push:
    tags:
      - "v[1-9]+.[0-9]+.[0-9]+"
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ~1.22.2

      - name: Gather dependencies
        run: go mod download

      - name: Test
        run: |
          mkdir testResults
          go test -count=1 -p=1 ./... -v -coverprofile testResults/coverage.out -coverpkg=./...
          cat testResults/coverage.out | grep -vE '.*stores/login/.*' > testResults/finalCoverage.txt

      - name: Get test coverage report
        run: |
          go tool cover -func=testResults/coverage.out
          go tool cover -func=testResults/finalCoverage.txt -o=testResults/finalCoverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}